#!/usr/bin/env python

import logging

from keyswarm import main

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logger = logging.getLogger()
    logger.debug('starting main function')
    main()
