#!/usr/bin/env python3
from multipass.ui import main
from multipass.gpg_handler import encrypt, list_packages, decrypt, get_recipients_from_gpg_id, list_available_keys
from multipass.pass_file_system import search_gpg_id_file

if __name__ == '__main__':
    #encrypt(b'1234fdsfdsfdsdsf5', ['rfr@mioso.com'], '/tmp/test.gpg')
    #print(list_packages('/tmp/test.gpg'))
    #print(decrypt('/tmp/test.gpg'))
    #print(get_recipients_from_gpg_id('/home/user/.password-store/.gpg-id'))
    #search_gpg_id_file('/home/user/.password-store/test2')
    #print(list_available_keys())
    main()
