# RSA Private Key tester@test.com 0x80035649BDABA4EC6A02E7D36BF58E6E9B697F1C passphrase = test
private_key = b'''LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbFFQR0JGMzFXc2NCQ0FESXh2
                  eEI3dnBURU5ZMjE1K21icVJZVG1nOVdya1EyUnFvS3hlOW1oSUUwbkc0UWN5YQoxRW9sQ0x5bEpG
                  MmlpdG5zZlBpV3dvRXhGUG5NbHl4ZzhTMG8vcXlJTTk5bEVVRWRyRlQxS2g1UVIvdW9FN3RwClhF
                  NXlOYlFkMUw3K0g4OEprekEwc1gxNHFDeklzTi9yOWU3TG94eDF1ekZvRzc4NnR2ZWZQZXd4TG1n
                  dzVZeEoKaUFaUHFoeUFjNFlMZFVydURpS0xXdGhLeWJDU1RaVXZoMTlhdnhuT3Z5d21ZUlduS1F6
                  bDZKYm1DVTdUMXlRbwpKWS8vWUNuNDFBeHN5WW4vNlNQcExMTXNHenA3NjB6NThqVlJrVkxRY2lw
                  MW9vQjNXVjhnZkIyT0VqaG45ejhyCmRnN09heXNQT094ZG9YT0Zpc05pWEY0Z2IxTGFKQllSbEw4
                  MUFCRUJBQUgrQndNQ0FTY3kxR1N1MHJQcjlnZGoKc2xEdjRSUDNVRXcvZHJhSzBUam1VbFQrRFMy
                  U1RQcFpWdmV3NGU5a1NtT2xXYzkvTzUydndrUU82WmFEeFZJSQoxcitrMERydndBZFpTNFNtTnpn
                  TWk0dzdGejVxekJSL1VFLzZHTFBxYU5TdENVbjZwekVPTmoxRThZOERsY3BxClBTU3VCdlBMdmov
                  alhrdjE1RWZWc0xWS1lHQUN0QmhtcnZseFJ6ck02T2lSTklLa2Z1YzBtUGhpSkNnQW9pelMKUjNY
                  NVBTUmVnczBqQkJ1TkE1RS8xSk01bmVRZEZ3UU5iRzFNZitsaE5KM2RZeG5qWmxqQ1JuNEtobDJX
                  QU40bgpERjFmTzlKWWtaT1BOSEFzb3FXOXdzTEFsZWcwWXZIdmtreEVvMklicUVGVjlMKzRqbjVM
                  NzZOcTdWd3lYUlQ2CkV4TDlDU2pabW82eGdlNjhQOUxQNU01cm4yS3FwOHp4dHJubVJoZFN3c0c2
                  L1RFL1AyQlRnTDdqSXlBMVBoZjIKNXQweCthK3lZMkN2aXpTZEZqSFlMSmVqMHEvek9hY25ESEZh
                  dGhNTGRUTkpSdVkra0tndHN1bEhLcW5kdjdnSwphcTJDTVdtWDhwekN6N1BMbFQ0NzFvdWExUVhW
                  NElTTjVwdE1FeVlSVUV6Rkk4QkgvNlJjNEpudVFJbk5kOFNQCmx0c2FXb09nTUNrcktjZ0VYZXJn
                  SC84dkVpS1FzYUhpM3dBSDUzVWRoZXlRZTREbTlITi85ZWs2ZnoraDVSRG8KUHFROGsrZDBLQVJQ
                  T1lyaG00KzhEWURJZmtwenJnUkJJRXo0YTJIU1ozc2RDem5tTDNUR0NYaHd5SldFS3F6VgpUMUc2
                  azVVK2tQQkl1RUgvTUlUZzZLQlNsdlE0NVNrQkxRMi9rMzdWZnk5V0FVeFFzQ0JtdHFGZjRnbHFF
                  Rm1LClRvUnFlOXUxeFpTckNiY1E0elNXNTlIQlY2R0ZwWUJJazRFdERHRnZDTUVZL2VZUjROd292
                  b3hMYVJEb05VVFYKNTZvZDdrT1ltdVVrTVZxdDVwUXJIUnJCRHJRMVFTU28rTGRSOS9YRXVZTDJs
                  M0hrRU1VMkFPNVl6bWIyWUhTagpZQkRIenBoMmVZVy94MUxWWWJZYTdCckozbk12aHRjVUdTRVNJ
                  L1MrWWw3bDI4UHo4QXF3V0srY1N4UVBHSUZwCjVpaHhUcU9jZXdQY3RCaDBaWE4wWlhJZ1BIUmxj
                  M1JsY2tCMFpYTjBMbU52YlQ2SkFVNEVFd0VJQURnV0lRU0EKQTFaSnZhdWs3R29DNTlOcjlZNXVt
                  MmwvSEFVQ1hmVmF4d0liQXdVTENRZ0hBZ1lWQ0FrS0N3SUVGZ0lEQVFJZQpBUUlYZ0FBS0NSQnI5
                  WTV1bTJsL0hQU3dDQUNZcXVrRUtrMjd4SmhRTzB2dEFnVTZQZVkvUTExQUdrdDZsR05xCmdscmN6
                  Yk1BeU9jbFU3a1VKdHFnUmRyZ1JyaHZmRk5XNE9TcWdDbUVwOE9DM21qeHdEQ3RhajIvTXBjTEt1
                  R0QKM3NQcm5hUU03SDZuUFdGcGc5RTdsS2loc1ZqNm1NTVlJbmVqelp3M28xUytLN0RnWTBsa1NB
                  a3ExYUFocHlSZgpRSm5xQWxuajNCb09mbmhxZHVSWFBIU3gwek9JRkxjUHVFeEZDajdPSjRpazl4
                  aTdaQnZwQTNnWGlzR3NhTWtmCmdGUTZwQm9WMjVGeXRNVm9GaXFhdGZDS2JXbzRzbnEwZWhBcnVB
                  V3YyZCtnVG5WbVBrVGcreWdiSkVpRWxHcmEKMlF5cFNRYXNpVEtuV3R6ZWJXWXFTVTBoWERhZkVt
                  ZkdGK1dCMmJ4THFjOXlmQkprblFQR0JGMzFXc2NCQ0FDcwpycWFXZm5rOFZuQkF5Y0xNamZONjhT
                  ckNXTjFUd3JrU1g2YUdmcStaK3lzejM4SW9mQ1p2Q2g1Z012QjdQcjRVCmNETjNoZ01QTUZoZ3hz
                  ZmRiRHJRTHBxUjVleklVZzJnWW54KzFTQjYzL05wdkgxSUdINk9SNDltWEI4U0dCS1kKdnVCNFhJ
                  OTlUcWZQUkFXWmlTUG8yRnhMRTI0bVB0NkpjUUYvclovS1I4emViQzI4MXN6c3YrdithUjlzNkxU
                  QgpCaDYxQ0pycjZZaUVkUEhrbmRySDd0QkpIeEVFbUNFRkhKTHJxUkI4UDllYlpnQWFiZGR0VURt
                  a2RGZ0hXcDAyCitab2F5NEpuTStBZnlWK2lZQXJXQ2orYzNKWURhQlExQ2d2M0x4cEJGRGJDNmV0
                  SDVIRERrYXIzV3N5SXloZ2YKQjd4MXdzM3I4SlRvLzV2UE43YkhBQkVCQUFIK0J3TUMwdWhOSTBw
                  ZGxMM3J2N0RxYk90bXFLdUNadG5pazUzSQpsRlVXNDFQNFlteTNLSEtqL0JQYStsNGpsRXBDejJa
                  R1ZFVVRDeGxSRjlxaVJ3cDJra1QrTXB1dFJQVmZYL0hTCmlvSmUvRXMvL01DaDI2YzhhN1JMOUxQ
                  QzFYMngzOXJGdTNVQlVHUVByQnVWTW1MYjZRWVkyT1AwcmtXaGxyeHgKMUlmWHQyOU1USmpkNGVn
                  bk56Q3JMWlFGUmZDdDhnd0JVSzkvUWJFNkpDTmZpV25RcWJpSmZrVEExOC80V2MvcgpnS3Q0SXR4
                  WWRyVlJicEFPc2phbFRwMlU4YWdkbE9OMGhCQmlyLzlXckErb2dKZHNDbGdqNjFjVkNLSEJzZmxk
                  CjJpd1hxd3BtQTZYNFZaZjZINHdwM2RqQVdPbXQ2eVJFSjk2bEtDUlZrUE16Q29BK0VLK2tHeXRS
                  cktNdVBzYnAKYmhjZlVCM2t6V1dxK0NTQXM3L2MyeGY4a1huYWVtTXBFTDEwaEJWaGpKNG9mRk5m
                  cEFOdDEzYnRKaDFiSVgxUQpJQ3ZReVVGWHVQUGZ4UzFEeXNXTGh4MGVaUXo5QjJCMkhGL3kxS2tZ
                  aUwyamZJTWlGWEVqTUpmR3Z0RzVsS3B5ClI0UlpPS2REaDVsaUNFK2tMd290Y1htTy9sQWJzY053
                  bmhCSjZLcjRtelZOOXh5dHlIYWh2WGFueFh1dmZTa0wKNjlLdHZHREZqSDA1R0xFd2x0QVJxTEo1
                  M2tacERHZDRhQzRUTEVVUnRFWVZ4VmxpM0JwY2JlSjlHd0duWDlpSQpqNUNtWVpwWHkxeVVvc1hM
                  RURKdlRpTXZQWW5wWnhvY05TRk9OTW9sbmdhcHFzL0pRdjFsUWlKZHVtT285T2h4CmpKbXlKS1I0
                  cUtlUHFKN0VITDhSeHhGWWFXdVdudGI2V09lZlpzLzJZcTB2YUwxc1Y1VXFBU2k1RWVXTDFrNWkK
                  TkpWZWVMSkJ5WXZEMTMzTU40N3R4bmpNLzZWRzNpTjhoeW92WU96OWptK0xhekxrck5leTZZZVBj
                  Q2F4ZnJGSgpVbXRBQUl3S0JHckdBZ1EvMGIwMlZQZEVQSk91RFlIbDU3SmpJeTN4WDJsK1krUGhY
                  N0N1NXZFU2ZKcDFmWGxTCjFuREtYRHR1TURQcXgrQjU4dmpHS1FPRGh4KzZPamZ2NnJSRXJsbEVM
                  UGVLNlRhYVZxVzlFTHMybE5SQmlRRTIKQkJnQkNBQWdGaUVFZ0FOV1NiMnJwT3hxQXVmVGEvV09i
                  cHRwZnh3RkFsMzFXc2NDR3d3QUNna1FhL1dPYnB0cApmeHpkdFFmL1NVUXZkVEFoWEQ4aXBOcHF2
                  OTloWXZEV0V0d1VyQ05IbGxzZ3dyQUNrTnBEYUxrbnBsSnI5eGMyCkkvWUVwaHoyYTdTMmpRNG9l
                  VVV3S2pXR3NDK1NVMUJTam1mVmV2U3BUamNWazZsbEZWWHZoZnBwMlZHRUJjNFYKRlBvRmQ4dEgy
                  L1lYSVJBMlg3VUlpei9meTk2NEN4K3gwKzBpeGUxQXFiMmFPZDFrMHowbUtVZ1B1SjRIQk9BLwps
                  WHl6WmFGVVM1MjJyMUI3VkRLbytlK0hpSFFZdlZFN1RpT05RSUpRQVlJb2xVRWxvK2phUU5QcFUy
                  L0pJL3l2CmtMYWc1cFRYSkJucTNzcFdaUGlvOTc4T2xYeVRBRS9KSnFtU3lwUVVxZnlsbk5NMVc2
                  QUhyb1BncHZYdWpVZzMKK3kxb3E3M3Z6VXFhaVJHOWF1Uk9Ldm9yQjZleG1BPT0KPXhjZEYKLS0t
                  LS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K'''

# a cyphertext decrypting to "test" encryptet to tester@test.com
encrypted_file = b'''hQEMAzBMSLRL1jTgAQf/Uqkp4ZrI2pENuYhZT6frS3mwpp6vsBcHDmpA0VWJHA7/XJIgym4a9qEE
                     nGsUPmInlLQFU5NwpmoOlbgqZJvy3tNMUQ/xAtLtqbHIUr9D6V03qDHTHnr6OSx9w+y/tBhwHhWy
                     hJU4iKk4muvhFBugFPWuFFxAh4gEZYnYQzTHR5BB3y3kwvz1r9UwR4DQuJ4wSHI++JKtcijii0Lf
                     /KItbAs/8hZqNNIB339onsqDVMH5JqXLC/AF+kKsDvIXmfj5/jI6d+ouHDfAbbc2AAwci1RfVQOo
                     GsmJjC7zmCUigQO/hITao4x/AKauUPTTjyCyYrBEpg0kTpiLwb7hOinUm9I/AbJn0hcdtxHigwQx
                     7gwq+DNPMeFA7RetZiOHhdqbAuh/QGvA5RECdDOa+zMqEPMd0GgOjogpZ6Aeql5/P4Cv'''

# a eddsa ed2557 private key tester2@test.com 0xA76F69733F4FBE97A4553B7C414129BA435C3226 passphrase = test
eddsa_private_key = b'''LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbElZRVhmeVVHeFlKS3dZQkJBSGFSdzhCQVFkQUdNT
                        EUwWFVZTEZrNkxxSWI1UE04TVEzVFN6cTRpZTlrSGp6WAp6ek1qZndQK0J3TUNwb3dsUDg5cVQwUHJNQzBUaWJxR29vQ1
                        c0OEp5OGtRWEtlbGR4RDY2VkNNaDVBNzNHdTZlCmtBNDR6bDljYWNXRE5sRE80bmJ0emNDZTFVeHRYbFFQcFRUUWsxMUJ
                        GazZobXI0RHJrZnd3TFFhZEdWemRHVnkKTWlBOGRHVnpkR1Z5TWtCMFpYTjBMbU52YlQ2SWtBUVRGZ2dBT0JZaEJLZHZh
                        WE0vVDc2WHBGVTdmRUZCS2JwRApYREltQlFKZC9KUWJBaHNEQlFzSkNBY0NCaFVJQ1FvTEFnUVdBZ01CQWg0QkFoZUFBQ
                        W9KRUVGQkticERYREltClVvc0JBTW1RZ3pFOGxOUjhCQjNKZCtUWlhHNTRUYVZjdWRQWm1GaXRnZ3pmV09qQ0FRRFlPbF
                        g4cUM3bWhWOTIKYzdmenJTU0ZSejliVjlvTXVnMnBYVEhHOVlUNURKeUxCRjM4bEJzU0Npc0dBUVFCbDFVQkJRRUJCMEE
                        5QWxucwpndW5rNFo4RXRrN3RYNkdRdmFwQ2pEV28yMHlsYTJndU92NzFSQU1CQ0FmK0J3TUNnZ1U0cU04aTNMTHJ1Y2U1
                        ClJEYkxFcWNiRHQ0KzJ3dVViRThRN1lWditxOHg1R3BTN05RTGZYVGVRNHVaamdKY0pkQmpIclBJTHZTWmVoKzMKSkMyM
                        TRIbW5EcHBDMU5lVlpUVVl5d0hXM0loNEJCZ1dDQUFnRmlFRXAyOXBjejlQdnBla1ZUdDhRVUVwdWtOYwpNaVlGQWwzOG
                        xCc0NHd3dBQ2drUVFVRXB1a05jTWlidjFBRUE4eHpJWGpXSVcwd1BHK21xK0ZCRWdvc0UwR3ZiCnZjYnRvbkJSNDdPZit
                        MSUJBUFd0SWVuWmNnVEN1WUFIWDZPNWhPR2d3ZXVRRzdaZ2pYSGZYZ1lGb1RrSQo9YzVNVAotLS0tLUVORCBQR1AgUFJJ
                        VkFURSBLRVkgQkxPQ0stLS0tLQo='''
